#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
 Author: shiliangliang
 Date: 2020.03.26
 Desc: make template files from the templates  
       python new [test1.py test2.py tp.sh]
'''
from sys import argv
from os.path import join, dirname, exists
from time import strftime

replaces = {'$AUTHOR': 'shiliangliang',
            '$DATE': strftime('%Y.%m.%d'),
}

root_dir = join(dirname(__file__), 'templates')
def read_template(suffix):
    file_name = join(root_dir, 'template.'+suffix)
    if exists(file_name):
        with open(file_name) as f:
            txt = f.read()
        return txt
    else:
        return ''
    

for file_name in argv[1:]:
    if not exists(file_name):
        if '.' not in file_name:
            print(file_name + ' has no type.')
            continue
        suffix = file_name.split('.')[-1]
        txt = read_template(suffix)
        for i in replaces:
            txt = txt.replace(i, replaces[i])
        with open(file_name, 'w') as f:
            f.write(txt)
    else:
        print(file_name + ' already exists.')
